name: safe_vault
description: "Application mobile de gestion et sÃ©curisation des mots de passe."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  path: ^1.9.1
  pointycastle: ^4.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  sqflite_sqlcipher: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
