name: safe_vault
description: "Application mobile de gestion et sÃ©curisation des mots de passe."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.3
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  sleek_circular_slider: ^2.1.0
  sqflite_sqlcipher: ^3.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
