name: safe_vault
description: "Application mobile de gestion et s√©curisation des mots de passe."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  convert: ^3.1.2
  flutter:
    sdk: flutter

  flutter_secure_storage: ^10.0.0
  http: ^1.6.0
  local_auth: ^3.0.0
  path: ^1.9.1
  pointycastle: ^4.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  sqflite_sqlcipher: ^3.4.0
  flutter_svg: ^2.2.3
  sleek_circular_slider: ^2.1.0
  awesome_snackbar_content: ^0.1.8
  no_screenshot: ^0.3.1
  flutter_native_splash: ^2.4.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true
  web: false

  android_12:
    color: "#ffffff"
    android: true
    ios: true
    web: false
